/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package bridge

import ca.attractors.deck.Card
import ca.attractors.deck.Deck
import org.junit.jupiter.api.Test;

class DistributorTest {
    @Test void testX() {
        def distributor = new Distributor()
        def setup = { Distributor distributor1 ->
//            distributor.addNorth(Card.getAceOfClubs())
//            println("In Setup")
        }
        distributor.setCondition {
            it.getNorth().contains(Card.getKingOfSpades())
        }
        distributor.setSetUp(setup)
        distributor.simulate()
    }
}
